// Auto-generated by better-auth-studio
// You can customize this file if needed

import { createStudioHandler } from 'better-auth-studio/nextjs';
import { auth } from '@/lib/auth';

const handler = createStudioHandler({
  auth,
  basePath: '/api/studio',
  // Access control temporarily disabled for testing
  // Uncomment and customize after initial setup:
  // allowAccess: async (session) => {
  //   return session?.user?.role === 'admin';
  // },
});

// Export for all HTTP methods
export {
  handler as GET,
  handler as POST,
  handler as PUT,
  handler as DELETE,
  handler as PATCH,
};
